import type { Metadata } from "next";
import { createClient } from "@/utils/supabase/server";

export const metadata: Metadata = {
  title: "Exploration 4",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient()

  const user = await supabase.auth.getUser()
  // console.log(data.user?.email)

  const profile = await supabase
    .from('profiles')
    .select()
    .eq('id', user.data.user?.id)
  
  console.log(profile.data)

  

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
