import type { Metadata } from "next";
import { createClient } from "@/utils/supabase/server";

import { ProfileProvider } from "@/contexts/profileContext";

import { Profile } from "@/types/profile";

export const metadata: Metadata = {
  title: "Exploration 4",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ProfileProvider profile={await getProfile()}>
        <body>{children}</body>
      </ProfileProvider>
      
    </html>
  );

  async function getProfile() : Promise<Profile | undefined> {
      
    const supabase = await createClient()

    const user = await supabase.auth.getUser()
    // console.log(data.user?.email)

    const data = await supabase
      .from('profiles')
      .select()
      .eq('id', user.data.user?.id)
    
    console.log(data.data)

    let profile = undefined

    if(data.data && data.data.length > 0){
      profile = data.data[0]
    }
    
    return profile
  }
}
